modify postBuild for geckodriver

diff --git a/postBuild b/postBuild
--- a/postBuild
+++ b/postBuild
@@ -1,43 +1,18 @@
-#!/usr/bin/env bash
-# https://developers.supportbee.com/blog/setting-up-cucumber-to-run-with-Chrome-on-Linux/
-# https://gist.github.com/curtismcmullan/7be1a8c1c841a9d8db2c
-# http://stackoverflow.com/questions/10792403/how-do-i-get-chrome-working-with-selenium-using-php-webdriver
-# http://stackoverflow.com/questions/26133486/how-to-specify-binary-path-for-remote-chromedriver-in-codeception
-# http://stackoverflow.com/questions/40262682/how-to-run-selenium-3-x-with-chrome-driver-through-terminal
-# http://askubuntu.com/questions/760085/how-do-you-install-google-chrome-on-ubuntu-16-04
+#!/bin/bash
+# download and install latest geckodriver for linux or mac.
+# required for selenium to drive a firefox browser.
 
-# Versions
-CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
-SELENIUM_STANDALONE_VERSION=3.4.0
-SELENIUM_SUBDIR=$(echo "$SELENIUM_STANDALONE_VERSION" | cut -d"." -f-2)
-
-# Remove existing downloads and binaries so we can start from scratch.
-sudo apt-get remove google-chrome-stable
-rm ~/selenium-server-standalone-*.jar
-rm ~/chromedriver_linux64.zip
-sudo rm /usr/local/bin/chromedriver
-sudo rm /usr/local/bin/selenium-server-standalone.jar
-
-# Install dependencies.
-sudo apt-get update
-sudo apt-get install -y unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
-
-# Install Chrome.
-sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
-sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
-sudo apt-get -y update
-sudo apt-get -y install google-chrome-stable
-
-# Install ChromeDriver.
-wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
-unzip ~/chromedriver_linux64.zip -d ~/
-rm ~/chromedriver_linux64.zip
-sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
-sudo chown root:root /usr/local/bin/chromedriver
-sudo chmod 0755 /usr/local/bin/chromedriver
-
-# Install Selenium.
-wget -N http://selenium-release.storage.googleapis.com/$SELENIUM_SUBDIR/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar -P ~/
-sudo mv -f ~/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar /usr/local/bin/selenium-server-standalone.jar
-sudo chown root:root /usr/local/bin/selenium-server-standalone.jar
-sudo chmod 0755 /usr/local/bin/selenium-server-standalone.jar
+install_dir="/usr/local/bin"
+json=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest)
+if [[ $(uname) == "Darwin" ]]; then
+    url=$(echo "$json" | jq -r '.assets[].browser_download_url | select(contains("macos"))')
+elif [[ $(uname) == "Linux" ]]; then
+    url=$(echo "$json" | jq -r '.assets[].browser_download_url | select(contains("linux64"))')
+else
+    echo "can't determine OS"
+    exit 1
+fi
+curl -s -L "$url" | tar -xz
+chmod +x geckodriver
+mv geckodriver "$install_dir"
+echo "installed geckodriver binary in $install_dir"
